# Generated by Django 4.2.11 on 2024-06-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_follower_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
