# Generated by Django 4.2.11 on 2024-06-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_like_timestamp_like_is_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
